name: Lint and format

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Python info
      shell: bash -l {0}
      run: |
        which python3
        python3 --version
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Install Ruff
      run: python3 -m pip install ruff
    - name: Check style against standards
      run: ruff check src/ --no-fix

  format:
    name: Code formatting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Python info
      shell: bash -l {0}
      run: |
        which python3
        python3 --version
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Install Ruff
      run: python3 -m pip install ruff
    - name: Check style against standards
      run: ruff format src/ --check
      
  build:
    name: Build the package, check typing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Python info
      shell: bash -l {0}
      run: |
        which python3
        python3 --version
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Install workflow package
      run: python3 -m pip install .[dev]
    - name: Check typing
      run: mypy src/ --install-types --non-interactive
